# Generated by Django 4.2.4 on 2023-08-26 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('name', models.CharField(help_text='Kampaniya nomini yozing', max_length=255)),
                ('description', models.TextField(help_text='Kamnaiya haqida yozing')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('name', models.CharField(help_text='Reklama sarlavhasi', max_length=255)),
                ('description', models.TextField(help_text='Bu yerga reklama matni')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('name', models.CharField(help_text='Kategoriya nomi', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('first_name', models.CharField(help_text='Foydalanuvchining ismi', max_length=255)),
                ('last_name', models.CharField(help_text='Foydalanuvchining familiyasi', max_length=255)),
                ('phone', models.CharField(help_text='Foydalanuvchining telfon raqami', max_length=13)),
                ('city', models.CharField(choices=[('Toshkent shahar', 'Toshkent shahar'), ('Toshkent viloyati', 'Toshkent viloyati'), ('Andijon', 'Andijon'), ('Buxoro', 'Buxoro'), ("Farg'ona", "Farg'ona"), ('Jizzax', 'Jizzax'), ('Xorazm', 'Xorazm'), ('Namangan', 'Namangan'), ('Navoiy', 'Navoiy'), ('Qashqadaryo', 'Qashqadaryo'), ('Surxandaryo', 'Surxandaryo'), ('Sirdaryo', 'Sirdaryo'), ('Samarqand', 'Samarqand'), ("Qoraqalpog'istion Respublikasi", "Qoraqalpog'istion Respublikasi")], help_text='Foydalanuvchining viloyatini tanlang', max_length=50)),
                ('address', models.TextField(help_text='Foydalanuvchining aniq manzilini kiriting')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(help_text="Darslik uchun qo'shimcha tarif")),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('name', models.CharField(help_text='Maxsulotning nomini kiriting', max_length=255)),
                ('description', models.TextField(help_text='Maxsulot haqida')),
                ('price', models.PositiveBigIntegerField(default=0, help_text="Maxsulot narxini kiriting (so'mda)")),
                ('qty', models.PositiveIntegerField(help_text='Maxsulotning miqdorini kiriting')),
                ('category_id', models.ForeignKey(help_text='Kategoriyani tanlang', on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('description', models.TextField(help_text='Natijaga tarif bering')),
                ('product_id', models.ForeignKey(help_text='Maxsulotni tanlang', on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('full_name', models.CharField(help_text="Foydalanuvchining telegramdagi to'lq ismi", max_length=255)),
                ('user_name', models.CharField(blank=True, help_text='Foydalanuvchining telegramdagi username', max_length=255, null=True)),
                ('telegram_id', models.PositiveIntegerField(default=0, help_text='Foydalanuvchining telegram idsi')),
                ('client_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('description', models.TextField(help_text="Qo'llanma haqida matin kiriting")),
                ('product_id', models.ForeignKey(help_text='Maxsulotning tanlang', on_delete=django.db.models.deletion.CASCADE, related_name='instruction', to='shop.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('name', models.CharField(help_text='File nomini kiriting', max_length=255)),
                ('file', models.FileField(help_text='Rasim yoki video yuklang', upload_to='files/')),
                ('about_id', models.ForeignKey(blank=True, help_text='Kampaniya nomini tanlang (ixtyoriy)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file', to='shop.about')),
                ('banner_id', models.ForeignKey(blank=True, help_text='Reklamani tanlang (ixtyoriy)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file', to='shop.banner')),
                ('instruction_id', models.ForeignKey(blank=True, help_text="Dorini ishlatish bo'yicha qo'llamani tanlang (ixtyoriy)", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file', to='shop.instruction')),
                ('lesson_id', models.ForeignKey(blank=True, help_text='Darslikni tanlang (ixtyoriy)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file', to='shop.lesson')),
                ('product_id', models.ForeignKey(blank=True, help_text='Maxsulotning tanlang (ixtyoriy)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file', to='shop.product')),
                ('result_id', models.ForeignKey(blank=True, help_text='Maxsulot natijasini tanlang (ixtyoriy)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file', to='shop.result')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='client',
            name='product_id',
            field=models.ForeignKey(blank=True, help_text='Maxsulotni tanlang', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product'),
        ),
    ]
