# Generated by Django 4.2.4 on 2023-08-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(help_text='Darslikning nomi', max_length=255),
        ),
    ]
