# Generated by Django 4.2.4 on 2023-08-26 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_about_created_at_alter_about_update_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='update_at',
            new_name='update',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='update_at',
            new_name='update',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='update_at',
            new_name='update',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='update_at',
            new_name='update',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='update_at',
            new_name='update',
        ),
        migrations.RenameField(
            model_name='instruction',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='instruction',
            old_name='update_at',
            new_name='update',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='update_at',
            new_name='update',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='update_at',
            new_name='update',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='update_at',
            new_name='update',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='update_at',
            new_name='update',
        ),
    ]
